site_name: Atlas
repo_url: https://github.com/eanderson-ei/gtm-dms-alpha
edit_uri: edit/main/docs/
site_description: Activity-level data management solutions for the full data lifecycle. 
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes # (allows pages associated with section groups)
    - search.share
    - search.suggest
    - search.highlight
  font:
    text: Source Sans Pro
extra:
  generator: false
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.snippets
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Page tree
nav:
  - 'Home': 'index.md' 
  - 'Get Started':
    - 'Setup Overview': 'pages/get-started/overview.md'
    - 'Requirements': 'pages/get-started/requirements.md'
    - 'Setup': 
      - 'Set Up Data Steward Admin Tool': 'pages/get-started/setup/setup-admin.md'
      - 'Set Up Atlas Directory': 'pages/get-started/setup/setup-drive.md'
      - 'Set Up Imports': 'pages/get-started/setup/setup-imports.md'
      - 'Set Up Web Applications': 'pages/get-started/setup/setup-webapps.md'
      - 'Next Steps': 'pages/get-started/setup/setup-next-steps.md'
    - 'Optional Setup':
      - 'Install Postgres': 'pages/get-started/setup-optional/install-postgres.md'
      - 'Set up Mission Database': 'pages/get-started/setup-optional/setup-missiondb.md'
  - 'Usage':
    - 'Usage Overview': 'pages/usage/overview.md'
    - 'Update Thematic Database': 'pages/usage/update-thematicdb.md'
    - 'Update Activity Database': 'pages/usage/update-activitydb.md'
    - 'Onboard an Activity': 'pages/usage/onboard-activity.md'
    - 'Update Mission Database': 'pages/usage/update-missiondb.md'
    - 'Update Atlas Documentation': 'pages/usage/update-docs.md'
  - 'Design':
    - 'Architecture': 
      - 'pages/design/Architecture/README.md'
      - 'Activity Data': 'pages/design/Architecture/Activity Data/README.md'
      - 'Activity Location Data': 'pages/design/Architecture/Activity Location Data/README.md'
      - 'Performance Measures': 'pages/design/Architecture/Performance Measures/README.md'
      - 'Thematic Data': 'pages/design/Architecture/Thematic Data/README.md'
    - 'Pipelines': 
      - 'pages/design/Pipelines/README.md'
      - 'Activity Data': 'pages/design/Pipelines/Activity Data/README.md'
      - 'Activity Location Data': 'pages/design/Pipelines/Activity Location Data/README.md'
      - 'Thematic Data': 'pages/design/Pipelines/Thematic Data/README.md'
    - 'Components': 
      - 'pages/components/index.md'
      - 'Data Steward Admin Tool': 'pages/components/data-steward-admin.md'
      - 'Activity Database': 'pages/components/activity-database.md'
      - 'Activity Folder': 'pages/components/activity-folder.md'
      - 'Activity Location Data Tracker': 'pages/components/activity-location-tracker.md'
      - 'Activity Location Data Compiler': 'pages/components/activity-location-compiler.md'
      - 'Thematic Database': 'pages/components/thematic-database.md'
      - 'Mission Database': 'pages/components/mission-database.md'
      - 'Data Catalog': 'pages/components/data-catalog.md'
      - 'Map Viewer': 'pages/components/map-viewer.md'
      - 'Activity Location Data Portal (Public)': 'pages/components/ald-portal-public.md'
      - 'Atlas Distribution Folder': 'pages/components/atlas-distro.md'
  - 'Knowledge':
    - 'Playbook':
      - 'pages/knowledge/playbook/index.md'
    - 'Tutorials':
      - 'Tableau': 'pages/knowledge/tutorials/tableau-tutorial.md'
      - 'Google Apps Script': 'pages/knowledge/tutorials/google-apps-script-tutorial.md'
    - 'Knowledge Base':
      - 'pages/knowledge/base/index.md'
      - 'Add PSQL to PATH': 'pages/knowledge/base/add-psql-to-path.md'
      - 'Continual Improvement': 'pages/knowledge/base/continual-improvement.md'
      - 'Coordinate Reference Systems': 'pages/knowledge/base/crs.md'
      - 'Database Options': 'pages/knowledge/base/database-rationale.md'
      - 'Encoding': 'pages/knowledge/base/encoding.md'
      - 'Google Apps Script': 'pages/knowledge/base/google-apps-script.md'
      - 'H3': 'pages/knowledge/base/h3.md'
      - 'IMPORTRANGE': 'pages/knowledge/base/importrange.md'
      - 'Naming Conventions': 'pages/knowledge/base/naming-conventions.md'
      - 'Null Values': 'pages/knowledge/base/null-values.md'
      - 'pgAdmin': 'pages/knowledge/base/pgAdmin.md'
      - 'PostgreSQL': 'pages/knowledge/base/postgres.md'
      - 'PSQL': 'pages/knowledge/base/psql.md'
      - 'Pipeline Options': 'pages/knowledge/base/data-pipeline-rationale.md'
      - 'raster2pgsql': 'pages/knowledge/base/raster2pgsql.md'
      - 'shp2pgsql': 'pages/knowledge/base/shp2pgsql.md'
      - 'SQL': 'pages/knowledge/base/SQL.md'
      - 'Staging Data': 'pages/knowledge/base/staging-data.md'
      - 'Stakeholder Engagement': 'pages/knowledge/base/stakeholder-engagement.md'
      - 'Trackers': 'pages/knowledge/base/trackers.md'
